export const ACTIONS_TYPES = {
  SET_CITY_INFO: 'SET_CITY_INFO',
  FAVORITE_CITIES: 'FAVORITE_CITIES',
  CHANGED_FAVORITE_CITIES: 'CHANGED_FAVORITE_CITIES',
  GET_CITY_INFO: 'GET_CITY_INFO',
  GET_CITY_CARDS: 'GET_CITY_CARDS',
}